### PR TITLE
[FIX] support `neoforge.mods.toml`

### PR DESCRIPTION
**Pull request by MattSturgeon**
Neoforge 20.5.0-beta (needed for 1.20.5) moved from `mods.toml` to `neoforge.mods.toml`.

This PR updates the upload pre-checks to support that.

### CODE REVIEW

**Comment by hypherionmc** [comment]
It's like you are reading my mind. I was literally thinking about this last night when neo released

**Review by hypherionmc — APPROVED** [review]

**Comment by hypherionmc** [comment]
@MattSturgeon would you be able to resolve the merge conflict there? You can bump the version to 2.1.3 and then we can do a release. This one is already breaking for some mods, so we need it (cause not everyone knows how to disable the check)

**Comment by MattSturgeon** [comment]
> @MattSturgeon would you be able to resolve the merge conflict there? You can bump the version to 2.1.3 and then we can do a release. This one is already breaking for some mods, so we need it (cause not everyone knows how to disable the check)

Sorry, away atm so might be slow to respond. This should be done though.

**Comment by hypherionmc** [comment]
No worries. Thank you :)

**Pull request merged**
